import { Injectable } from '@nestjs/common';

export interface NormalizedOcrPair {
  label: string;
  value: string;
}

export interface NormalizedOcrDocument {
  text: string;
  lines: string[];
  pairs: NormalizedOcrPair[];
}

@Injectable()
export class OcrTextNormalizerService {
  normalize(rawText: string): NormalizedOcrDocument {
    const text = rawText
      .replace(/\r/g, '\n')
      .replace(/Page\s+\d+\s+of\s+\d+/gi, '')
      .replace(/Generated By\(Date Time\)[^\n]*/gi, '')
      .replace(/Disclaimer:[\s\S]*?In Patient Services/gi, 'In Patient Services')
      .replace(/[ \t]{2,}/g, ' ')
      .replace(/[^\S\n]+:\s*/g, ': ')
      .replace(/\n{3,}/g, '\n\n')
      .trim();

    const lines = text
      .split('\n')
      .map((line) => line.trim())
      .filter(Boolean);

    const pairs = this.extractPairs(lines);

    return {
      text,
      lines,
      pairs
    };
  }

  findPairValue(
    pairs: NormalizedOcrPair[],
    candidateLabels: string[],
    options?: {
      includes?: boolean;
    }
  ): string {
    const normalizedCandidates = candidateLabels.map((label) => label.toLowerCase());

    for (const pair of pairs) {
      const normalizedLabel = pair.label.toLowerCase();
      const isMatch = normalizedCandidates.some((candidate) =>
        options?.includes ? normalizedLabel.includes(candidate) : normalizedLabel === candidate
      );

      if (isMatch && pair.value) {
        return pair.value;
      }
    }

    return '';
  }

  private extractPairs(lines: string[]): NormalizedOcrPair[] {
    const pairs: NormalizedOcrPair[] = [];

    for (const line of lines) {
      const direct = line.match(/^([A-Za-z][A-Za-z0-9 /&().,'-]{2,40})\s*:\s*(.+)$/);
      if (direct) {
        pairs.push({
          label: direct[1].trim(),
          value: direct[2].trim()
        });
        continue;
      }

      const reverse = line.match(/^(.+?)\s*:\s*([A-Za-z][A-Za-z0-9 /&().,'-]{2,40})$/);
      if (reverse) {
        pairs.push({
          label: reverse[2].trim(),
          value: reverse[1].trim()
        });
      }
    }

    return pairs;
  }
}
